PACKAGE_NAME="dsvram"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="dsvram_drv"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"
